### PR TITLE
Open routed URL in a new tab

### PR DESCRIPTION
**Pull request by xavierfacq**
Try to fix issue #272

### CODE REVIEW

**Comment by xavierfacq** [comment]
It seems to work in the deploy preview:

https://deploy-preview-339--eclipsefdn-adoptium-dash.netlify.app/trends

I'll just try to add the correct select Tab depending off the current route.

**Comment by xavierfacq** [comment]
:heavy_check_mark:  Rewritings are goods

But it's more complicated than I thought to activate the matched route. I'll do than in another PR.

**Comment by gdams** [comment]
@xavierfacq is there a reason you didn't go for @netomi's approach outlined here: https://github.com/adoptium/dash.adoptium.net/issues/272#issuecomment-1533004799

**Review by gdams — APPROVED** [review]

**Comment by xavierfacq** [comment]
> @xavierfacq is there a reason you didn't go for @netomi's approach outlined here: [#272 (comment)](https://github.com/adoptium/dash.adoptium.net/issues/272#issuecomment-1533004799)

I don't know HashRouter, but I know that rewriting works well and it was a quick fix for existing urls.

**Comment by netomi** [comment]
I tested the implemented solution and it works nice. I think its a better approach than the HashRouter.

**Pull request merged**
